[#18] Get the specific database OID by using the database name
pgmoneta/pgmoneta_ext pull request #19
Opened 2024-08-01 15:16 UTC by GuChad369

This new function `pgmoneta_ext_get_oid` can get the specific database `OID` by the database name.

The next step is to get the queries we need using this OID and then send them to the core, similar to how `pg_dump` operates.

After this, we can use the extension to achieve the specific database backup.

2024-08-01 15:33 UTC, jesperpedersen commented
You need a functions to get all database names as well, right ?

2024-08-01 15:35 UTC, GuChad369 commented
I am confused about why we need all the database names.

2024-08-01 15:39 UTC, GuChad369 commented
This is the test result: if we want to get the OID for `mydb`, it will return the OID of `mydb`.

![Screenshot 2024-08-01 at 11 38 18 AM](https://github.com/user-attachments/assets/1c2136a3-13db-41b5-9e36-8041ba7bebf6)

2024-08-01 15:54 UTC, jesperpedersen commented
Yeah, but if we do

```
...
[primary]
databases = *
```

then we need to know all the OIDs

2024-08-01 15:55 UTC, jesperpedersen commented
And, yes - that looks correct

2024-08-01 15:57 UTC, GuChad369 commented
Okay, I see. Thanks for explaining.

2024-08-02 14:21 UTC, GuChad369 commented
![Screenshot 2024-08-01 at 5 22 48 PM](https://github.com/user-attachments/assets/671a90ee-2445-4ff9-9cc6-77eb83ac6662)

This new function `pgmoneta_ext_get_oids` can return all OIDs on the current server.

2024-08-03 19:30 UTC, jesperpedersen requested changes

2024-08-03 19:30 UTC, jesperpedersen commented on src/include/utils.h
> +#include "nodes/pg_list.h"
Why `"` ?

2024-08-03 19:30 UTC, jesperpedersen commented on src/include/utils.h
> +typedef struct DbInfo
Use the asme style as core - e.g. without `typedef`

2024-08-03 19:30 UTC, jesperpedersen commented on src/pgmoneta_ext/utils.c
> +#include "access/genam.h"
Again, `"`

2024-08-04 18:32 UTC, jesperpedersen commented
You need the manual update

2024-08-06 13:40 UTC, merged

2024-08-06 13:40 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !