[#22] Receive file from client
pgmoneta/pgmoneta_ext pull request #25
Opened 2024-09-28 17:17 UTC by GuChad369

After trying several methods to send a file from the client, I will now use our extension to receive the file from the client. These are functions on the extension side, which will be called from the client side to send the file chunks. The logic is very similar to the `pgmoneta_ext_get_file` function.

2024-09-28 17:36 UTC, jesperpedersen commented
Would be better to do this in one function - as there could be concurrent operations using this API

2024-09-28 17:47 UTC, GuChad369 commented
The logic of using three functions is clearer than relying on just one. I am currently resolving concurrency issues to ensure that the `FileTransferContext` structure is isolated in different sessions. If necessary, we can also implement a locking mechanism.

2024-10-23 21:49 UTC, GuChad369 commented
I combined the separate functions into a single function, making it simpler to manage.

2024-10-24 06:11 UTC, jesperpedersen requested changes

2024-10-24 06:11 UTC, jesperpedersen commented on sql/pgmoneta_ext--0.1.0.sql
> +CREATE FUNCTION pgmoneta_ext_receive_file_chunk(base64_chunk text, file_path text) RETURNS int
You need to add this function to the documentation

2024-10-27 00:56 UTC, merged

2024-10-27 00:56 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !