[#3] Initial documentation
pgmoneta/pgmoneta_ext pull request #6
Opened 2024-05-22 11:24 UTC by GuChad369

Set up the `pgmoneta_ext` documentation skeleton and integrate the generation of HTML and PDF for the user and developer guides:

- doc/DEVELOPERS.md
- User guide
- Developer guide

2024-05-22 13:00 UTC, jesperpedersen requested changes

2024-05-22 13:00 UTC, jesperpedersen commented on README.md
> +The following commands will install `pgmoneta_ext` in the `/usr/local` hierarchy.
This need to install into the PostgreSQL setup...

2024-05-22 13:00 UTC, jesperpedersen commented on README.md
> +
Add information for debug build

2024-05-22 13:00 UTC, jesperpedersen commented on doc/DEVELOPERS.md
> +cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
Here again

2024-05-22 13:00 UTC, jesperpedersen commented on doc/manual/99-references.md
> +  [ask]: https://github.com/pgmoneta/pgmoneta/discussions
You need `pgmoneta_ext` here

2024-05-22 13:00 UTC, jesperpedersen commented on doc/manual/dev-01-install.md
> +\newpage
See pgmoneta -- this need to be a shared chapter

2024-05-22 13:00 UTC, jesperpedersen commented on doc/manual/dev-01-install.md
> +cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
Here again

2024-05-22 13:00 UTC, jesperpedersen commented on doc/manual/user-02-quickstart.md
> +The following commands will install `pgmoneta_ext` in the `/usr/local` hierarchy.
Here again

2024-05-22 13:02 UTC, jesperpedersen commented
You can add chapters like

* https://github.com/pgmoneta/pgmoneta/blob/main/doc/PR_GUIDE.md
* https://github.com/pgmoneta/pgmoneta/blob/main/doc/manual/dev-01-git.md

in as well

2024-05-22 13:04 UTC, jesperpedersen commented
You also need the `postgresql-devel` or `postgresql-server-devel` package

2024-05-22 23:51 UTC, GuChad369 commented on doc/manual/dev-01-install.md
> +\newpage
For `pgmoneta`, the installation process for developers is more detailed than for users, reflecting their different needs. Moving forward, I anticipate that the distinction between developers and users will remain, with users requiring only a quick start guide for this project.

2024-05-23 09:00 UTC, jesperpedersen requested changes

2024-05-23 09:00 UTC, jesperpedersen commented on doc/DEVELOPERS.md
> +for Fedora 38
For Fedora 40

2024-05-23 09:00 UTC, jesperpedersen commented on doc/DEVELOPERS.md
> +for Fedora 38, this will install PostgreSQL 15
38 -> 40

2024-05-23 09:00 UTC, jesperpedersen commented on doc/DEVELOPERS.md
> +dnf install git gcc cmake make
postgresql-server-devel

2024-05-23 09:00 UTC, jesperpedersen commented on doc/PR_GUIDE.md
> +Navigate to the directory where you wish to place the source code. In this example, we'll use `/usr/local/` as the base directory.
Use `$HOME/` instead

2024-05-23 09:00 UTC, jesperpedersen commented on doc/manual/98-acknowledgement.md
> +Contributions to `pgmoneta` are managed on [GitHub.com][pgmoneta]
Missing `_ext`

2024-05-23 09:00 UTC, jesperpedersen commented on doc/manual/dev-00-head.md
> +---
Use the new template from pgmoneta

2024-05-23 09:00 UTC, jesperpedersen commented on doc/manual/dev-01-install.md
> +for Fedora 38
For Fedora 40

2024-05-23 09:00 UTC, jesperpedersen commented on doc/manual/dev-01-install.md
> +dnf install postgresql-devel
postgresql-devel doesn't exist

2024-05-23 09:00 UTC, jesperpedersen commented on doc/manual/dev-01-install.md
> +for Fedora 38, this will install PostgreSQL 15
38 -> 40

2024-05-23 09:00 UTC, jesperpedersen commented on doc/manual/dev-01-install.md
> +dnf install git gcc cmake make
postgresql-server-devel

2024-05-23 09:00 UTC, jesperpedersen commented on doc/manual/user-00-head.md
> +---
Use the new template from pgmoneta

2024-05-23 09:04 UTC, jesperpedersen requested changes

2024-05-23 09:04 UTC, jesperpedersen commented on doc/DEVELOPERS.md
> +    SELECT pgmoneta_version_ext();
This should be `pgmoneta_ext_version()` instead

2024-05-23 09:13 UTC, jesperpedersen commented
We need a chapter in the user guide where all functions in the extension are documented, so only `pgmoneta_ext_version()` for now...

2024-05-23 09:50 UTC, jesperpedersen requested changes

2024-05-23 09:50 UTC, jesperpedersen commented on doc/DEVELOPERS.md
> +    SELECT pgmoneta_version_ext();
Still here

2024-05-23 09:50 UTC, jesperpedersen commented on doc/DEVELOPERS.md
> + pgmoneta_version_ext
And here

2024-05-23 09:50 UTC, jesperpedersen commented on README.md
The README.md still has `postgresql-devel` instead of `postgresql-server-devel`

2024-05-23 09:50 UTC, jesperpedersen commented on doc/manual/98-acknowledgement.md
> +[GitHub][pagmoneta] if you find it useful. And, feel free to follow
`pgmoneta_ext`

2024-05-23 10:24 UTC, jesperpedersen commented
`git grep pgmoneta_version_ext`

2024-05-23 12:54 UTC, merged

2024-05-23 12:57 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !