[#5] SQL: CHECKPOINT
pgmoneta/pgmoneta_ext pull request #8
Opened 2024-05-27 10:39 UTC by GuChad369

Create a wrapper function for the `CHECKPOINT` functionality:

- Define the function pgmoneta_ext_checkpoint in the SQL file.
- Implement the C code in lib.c.

Test result:
<img width="659" alt="Screenshot 2024-05-27 at 6 34 37 PM" src="https://github.com/pgmoneta/pgmoneta_ext/assets/113565433/79da6455-e6af-4872-b85f-fb15e59fc67b">

2024-05-27 11:22 UTC, jesperpedersen commented
You need to document the security aspect as well, as `CHECKPOINT` can only be executed by a superuser for PostgreSQL 13/14, and `pg_checkpoint` for PostgreSQL 15+.

Please, do testing using the 'repl' role from https://github.com/pgmoneta/pgmoneta/blob/main/doc/GETTING_STARTED.md

2024-06-02 21:15 UTC, GuChad369 commented
Simulate the process as described in [SQL: pg_switch_wal() #7](https://github.com/pgmoneta/pgmoneta_ext/pull/7), test the `CHECKPOINT` using the `repl` role, and perform security checks before executing the checkpoint.

postgres:
<img width="631" alt="Screenshot 2024-06-02 at 5 00 42 PM" src="https://github.com/pgmoneta/pgmoneta_ext/assets/113565433/b2eb4d59-5025-48e1-9d1a-05a0ac134691">

repl:
<img width="684" alt="Screenshot 2024-06-02 at 5 00 56 PM" src="https://github.com/pgmoneta/pgmoneta_ext/assets/113565433/c1b2ce53-eb97-4a44-b045-4606889edfee">

2024-06-03 05:04 UTC, jesperpedersen commented
You need to describe the `pg_checkpoint` for PostgreSQL 15+ - https://www.postgresql.org/docs/15/predefined-roles.html#PREDEFINED-ROLES-TABLE

2024-06-03 12:29 UTC, GuChad369 commented
The `RequestCheckpoint(CHECKPOINT_IMMEDIATE | CHECKPOINT_WAIT | CHECKPOINT_FORCE);` function can successfully force a checkpoint in both PostgreSQL 13 and PostgreSQL 15. 

This function does not have an inherent return value; the return value `CHECKPOINT` is custom-defined.

If necessary, we can customize the return value to be different depending on the version.

I tested it on both versions and obtained the same result. 

`postgres`:
<img width="1055" alt="Screenshot 2024-06-03 at 8 26 42 AM" src="https://github.com/pgmoneta/pgmoneta_ext/assets/113565433/4f9c95db-971d-4f07-8c04-1b09dc9acd2e">
<img width="1124" alt="Screenshot 2024-06-03 at 8 26 08 AM" src="https://github.com/pgmoneta/pgmoneta_ext/assets/113565433/f200e426-4e04-4fb1-9604-4148bc4acc49">


`repl`:
<img width="974" alt="Screenshot 2024-06-03 at 8 23 41 AM" src="https://github.com/pgmoneta/pgmoneta_ext/assets/113565433/29ce7085-2c7d-4860-ba7c-5d6fcd9d93c2">

<img width="955" alt="Screenshot 2024-06-03 at 8 24 21 AM" src="https://github.com/pgmoneta/pgmoneta_ext/assets/113565433/dd519e01-3308-485d-99f8-a8f3b9116ecd">

2024-06-03 15:17 UTC, jesperpedersen commented
I meant PostgreSQL 15+ has a built-in role called `pg_checkpoint` that you can assign to `repl` in order to make it work

2024-06-03 16:36 UTC, GuChad369 commented
- Add a new function `pgmoneta_ext_check_role` to check the specific role for the current user.
- Add security description in User Manual

2024-06-04 02:37 UTC, jesperpedersen requested changes

2024-06-04 02:37 UTC, jesperpedersen commented on src/pgmoneta_ext/utils.c
>  int
It would be better with an output parameter for the superuser role as a bool, and failure as the return value

2024-06-04 02:37 UTC, jesperpedersen commented on src/pgmoneta_ext/utils.c
> +pgmoneta_ext_check_role(Oid roleid, const char* rolename)
Same here...

It ties into #10

2024-06-06 05:57 UTC, merged

2024-06-06 05:59 UTC, Jubilee101 commented
Merged, thanks for your contribution!